# Generated by Django 5.2.11 on 2026-02-14 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0002_alter_friend_photo'),
        ('proposals', '0003_remove_proposal_attendees'),
        ('votes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='friend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='friends.friend'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='proposals.proposal'),
        ),
    ]
