# Generated by Django 5.2.11 on 2026-02-13 11:39

import friends.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='', validators=[friends.validators.validate_image_size]),
        ),
    ]
