# Generated by Django 5.2.11 on 2026-02-10 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('type_of_activity', models.CharField(help_text='Please enter the type of activity, e.g. "Eating out", "Bowling ect."', max_length=100)),
                ('proposed_date_and_time', models.DateTimeField(help_text='Please enter the proposed date and time of the event: ')),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Proposed', 'Proposed'), ('Confirmed', 'Confirmed'), ('Upcoming', 'Upcoming'), ('Past', 'Past'), ('Cancelled', 'Cancelled')], default='Proposed', help_text='Current status of the proposal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendees', models.ManyToManyField(blank=True, related_name='attending_proposals', to='friends.friend')),
            ],
        ),
    ]
