# Generated by Django 5.2.11 on 2026-02-12 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='place_of_event',
            field=models.URLField(blank=True, help_text='If you want, you can include a link to check the place:', null=True),
        ),
    ]
