# Generated by Django 5.2.11 on 2026-02-13 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0002_proposal_place_of_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='attendees',
        ),
    ]
