# Generated by Django 5.2.11 on 2026-02-15 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0003_remove_proposal_attendees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='status',
        ),
    ]
