# Generated by Django 5.2.11 on 2026-02-17 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0002_alter_friend_photo'),
        ('proposals', '0004_remove_proposal_status'),
        ('votes', '0002_alter_vote_friend_alter_vote_proposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='participants',
            field=models.ManyToManyField(related_name='proposals', through='votes.Vote', to='friends.friend'),
        ),
    ]
